Update bitvec dependency to  0.17.4
`cargo update` is giving me an error about bitvec.

```
cargo update
    Updating crates.io index
error: failed to select a version for the requirement `bitvec = "^0.15.2"`
  candidate versions found which didn't match: 0.17.4
  location searched: crates.io index
required by package `wagyu-ethereum v0.6.2`
    ... which is depended on by `myproject v0.1.0 (/home/ski/code/myproject)`
```

Importantly, 0.17.2's [changelog](https://github.com/myrrlyn/bitvec/blob/master/CHANGELOG.md#0172) says "This crash is considered a severe bug, as it indicates memory unsafety. Users are strongly encouraged to update to 0.17.2 immediately."

I haven't tested this yet, but I will soon.